In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
import pandas as p

In [6]:
features= p.read_csv('/Users/vikakumar/Desktop/test_ml_ola.csv')

In [7]:
import xgboost as xg

In [8]:
from sklearn import datasets

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
features.describe()

UserId      Order      Rating         ETA  Address_long  \
count  500.000000  500.00000  500.000000  500.000000    500.000000   
mean    50.500000    3.00000    2.972401   43.670562     43.625379   
std     28.894979    1.41563    1.187639   25.243204     24.563276   
min      1.000000    1.00000    1.004544    0.694558      1.068666   
25%     25.750000    2.00000    1.859763   21.562357     23.124494   
50%     50.500000    3.00000    2.993247   42.781270     43.088816   
75%     75.250000    4.00000    3.977902   65.241733     64.243317   
max    100.000000    5.00000    4.999795   86.915361     86.977991   

       Address_lat  Destination_long  Destination_lat  IsHomeHeading  \
count   500.000000        500.000000       500.000000       500.0000   
mean     44.470341         43.542779         0.510000         0.4800   
std      25.166625         24.632295         0.500401         0.5001   
min       0.795767          0.787326         0.000000         0.0000   
25%      22.534870         22.429746         0.000000         0.0000   
50%      45.627173         44.442767         1.000000         0.0000   
75%      65.989329         64.217968         1.000000         1.0000   
max      86.925005         86.605777         1.000000         1.0000   

       IsOnOtherTrip       DriverId  
count     500.000000     500.000000  
mean        0.536000   27434.000000  
std         0.499202   48281.487613  
min         0.000000      12.000000  
25%         0.000000     123.000000  
50%         1.000000    1234.000000  
75%         1.000000   12345.000000  
max         1.000000  123456.000000

In [11]:
features.head(5)

UserId  Order    Rating        ETA  Address_long  Address_lat  \
0       1      1  1.210885   1.003050     11.659150    85.905544   
1       1      2  4.808255  27.956061     45.876339    37.600352   
2       1      3  1.306195  60.017717     10.378658    41.438808   
3       1      4  1.060489  81.688770     77.475849    47.060443   
4       1      5  2.927480  19.893642     74.658619    59.828857   

   Destination_long  Destination_lat  IsHomeHeading  IsOnOtherTrip  DriverId  
0         72.007237                1              0              0    123456  
1         34.281540                0              1              0        12  
2         60.531052                0              1              1     12345  
3         28.999534                1              1              0      1234  
4          1.305024                0              1              1       123

In [12]:
np.array(features)

array([[1.00000000e+00, 1.00000000e+00, 1.21088486e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.23456000e+05],
       [1.00000000e+00, 2.00000000e+00, 4.80825515e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.20000000e+01],
       [1.00000000e+00, 3.00000000e+00, 1.30619470e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.23450000e+04],
       ...,
       [1.00000000e+02, 3.00000000e+00, 1.92918650e+00, ...,
        1.00000000e+00, 0.00000000e+00, 1.20000000e+01],
       [1.00000000e+02, 4.00000000e+00, 1.95141169e+00, ...,
        1.00000000e+00, 1.00000000e+00, 1.23450000e+04],
       [1.00000000e+02, 5.00000000e+00, 3.93434053e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.23000000e+02]])

In [13]:
labels = np.array(features['Order'])

In [14]:
features= features.drop('Order', axis = 1)

In [15]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels, test_size = 0.25, random_state = 42)

In [16]:
train_labels

array([3, 3, 4, 2, 5, 2, 4, 1, 2, 1, 3, 3, 5, 3, 1, 2, 4, 5, 5, 4, 2, 4,
       3, 2, 2, 1, 2, 1, 2, 3, 3, 4, 4, 1, 1, 1, 4, 4, 5, 3, 2, 2, 3, 4,
       4, 3, 3, 5, 4, 5, 1, 4, 2, 5, 5, 1, 1, 5, 1, 5, 2, 1, 3, 1, 4, 4,
       1, 1, 3, 5, 4, 1, 3, 3, 3, 3, 4, 1, 1, 4, 5, 4, 5, 4, 4, 1, 5, 1,
       5, 1, 5, 5, 1, 4, 5, 3, 5, 2, 2, 5, 5, 5, 5, 2, 5, 2, 5, 2, 2, 1,
       2, 4, 4, 1, 3, 4, 5, 5, 1, 1, 4, 2, 4, 5, 3, 5, 2, 5, 4, 3, 2, 2,
       3, 3, 3, 3, 4, 4, 2, 4, 5, 3, 3, 3, 3, 4, 3, 2, 1, 4, 2, 2, 1, 5,
       1, 3, 4, 4, 5, 5, 1, 5, 5, 2, 2, 1, 5, 2, 1, 3, 5, 3, 3, 3, 2, 3,
       4, 2, 5, 2, 3, 4, 3, 1, 1, 5, 5, 3, 3, 3, 1, 2, 3, 1, 1, 4, 3, 5,
       1, 1, 4, 1, 3, 2, 4, 5, 3, 1, 4, 1, 3, 4, 3, 2, 1, 2, 1, 5, 4, 4,
       2, 4, 2, 2, 3, 5, 3, 5, 2, 4, 1, 2, 5, 4, 2, 4, 3, 1, 2, 3, 3, 3,
       3, 1, 2, 3, 5, 1, 1, 4, 3, 1, 4, 3, 1, 4, 2, 4, 2, 4, 5, 1, 5, 2,
       1, 5, 4, 4, 2, 5, 5, 1, 3, 2, 3, 3, 1, 3, 2, 4, 2, 4, 1, 5, 2, 2,
       4, 3, 2, 1, 5, 5, 1, 4, 5, 2, 2, 3, 5, 5, 1,

In [17]:
from sklearn.ensemble import RandomForestRegressor

In [18]:
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

In [19]:
rf.fit(train_features, train_labels);

In [20]:
predictions = rf.predict(test_features)

In [21]:
predictions

array([3.296, 2.487, 2.34 , 2.437, 3.444, 3.137, 3.438, 3.058, 2.804,
       2.902, 2.879, 2.783, 2.916, 3.261, 2.472, 2.588, 3.004, 2.475,
       3.684, 3.085, 2.979, 3.18 , 3.564, 3.533, 2.716, 2.588, 3.028,
       2.979, 3.362, 2.475, 2.367, 2.93 , 3.021, 2.774, 3.311, 3.348,
       2.67 , 3.373, 2.833, 2.72 , 3.107, 2.684, 3.838, 3.296, 3.216,
       2.622, 2.551, 3.372, 2.796, 3.085, 3.341, 2.69 , 2.902, 2.79 ,
       2.803, 3.504, 3.154, 2.991, 2.759, 2.794, 3.175, 2.962, 3.189,
       3.22 , 3.313, 3.527, 2.153, 3.23 , 2.72 , 2.788, 2.932, 3.055,
       2.874, 2.588, 3.051, 3.084, 2.423, 3.5  , 3.026, 2.821, 2.957,
       3.448, 2.981, 2.957, 2.38 , 2.794, 2.436, 3.26 , 2.958, 3.281,
       2.948, 2.916, 3.187, 2.517, 2.812, 3.354, 2.545, 2.99 , 2.53 ,
       3.035, 3.129, 2.829, 2.881, 3.06 , 2.905, 3.275, 3.007, 2.423,
       3.005, 2.638, 2.836, 2.183, 2.564, 2.859, 3.093, 3.533, 2.872,
       3.425, 3.276, 3.105, 2.996, 2.702, 2.847, 2.983, 2.78 ])

In [22]:
test_features

UserId    Rating        ETA  Address_long  Address_lat  Destination_long  \
361      73  2.722559  30.285010     26.512827    59.658842         22.610038   
73       15  1.276612  65.625720     19.624659    47.531665         74.363344   
374      75  1.318004  76.145684     63.282971    11.510020         30.050435   
155      32  4.939759  41.790192     69.353336     6.545532         49.934759   
104      21  3.523647   7.557394     72.801245    45.078059         62.361131   
..      ...       ...        ...           ...          ...               ...   
220      45  4.155356  16.217887     25.456561    61.434418         84.090303   
176      36  3.454523   9.488681     59.708508    75.433650         56.420673   
320      65  1.534817   4.517420     62.250004    24.048257         69.092276   
153      31  4.498943  49.570034     58.999449    57.246626         61.056527   
231      47  3.989863  20.967675     29.783904     5.816421         57.132405   

     Destination_lat  IsHomeHeading  IsOnOtherTrip  DriverId  
361                0              1              0    123456  
73                 1              1              1        12  
374                1              1              0     12345  
155                1              0              1        12  
104                0              0              0    123456  
..               ...            ...            ...       ...  
220                1              1              0        12  
176                1              1              0        12  
320                0              0              0    123456  
153                1              0              1       123  
231                0              1              0      1234  

[125 rows x 10 columns]

In [23]:
features_predict= p.read_csv('/Users/vikakumar/Desktop/test_ml_ola_predict.csv')

In [2]:
features_predict.to_json('temp.json', orient='records', lines=True)

NameError: name 'features_predict' is not defined

In [24]:
rf.predict(features_predict)

array([2.583, 2.697, 2.51 , 3.075, 2.998])

In [25]:
import joblib as lib

In [26]:
lib_file = "/Users/vikakumar/Desktop/test_model_save.pkl"
lib.dump(rf, joblib_file)

['/Users/vikakumar/Desktop/test_model_save.pkl']